{
 "title": "PM2 Dashboard",
 "description": "pm2 metrics dashboard",
 "tags": [ "pm2" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values({job=~\"$job\"},instance) "
   }
  ]
 },
 "panels": [
  {
   "title": "pm2 list",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pm2_up{instance=~\"$host\"}) without(__name__,Time,exported_instance,job)"
    },
    {
     "expr": "sum(pm2_restarts{instance=~\"$host\"}) without(__name__,Time,exported_instance,job,id,instance,interpreter,node_version)"
    },
    {
     "expr": "sum(pm2_uptime{instance=~\"$host\"}/60/60) without(__name__,Time,exported_instance,job,id,instance,interpreter,node_version)"
    },
    {
     "expr": "sum(pm2_cpu{instance=~\"$host\"}) without(__name__,Time,exported_instance,job,id,instance,interpreter,node_version)"
    },
    {
     "expr": "sum(pm2_memory{instance=~\"$host\"}) without(__name__,Time,exported_instance,job,id,instance,interpreter,node_version)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pm2_cpu{instance=~\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pm2_memory{instance=~\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Restarts per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pm2_restarts{instance=~\"$host\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pm2_active_handles{instance=~\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "pm2_http_mean_latency{}", "legendFormat": "mean" },
    { "expr": "pm2_http_p95_latency{}", "legendFormat": "p95" }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "pm2_event_loop_latency{}", "legendFormat": "{{name}} - mean" },
    { "expr": "pm2_event_loop_latency_p95{}", "legendFormat": "{{name}} - p95" }
   ]
  }
 ]
}